blueprint:
  name: Purge History by Label (Daily)
  description: >-
    Purges the history for all entities assigned a specific label once daily (at a fixed time).
    This uses the `recorder.purge_entities` service. 
    Warning: Purging history is irreversible. Use with caution.
  source_url: "https://raw.githubusercontent.com/timzifer/hass-blueprints/main/purge_history_by_label_daily.yaml"
  domain: automation
  input:
    # Input for interval removed
    target_label:
      name: Target Label
      description: The label assigned to entities whose history should be purged.
      selector:
        text:
    keep_days:
      name: Keep Recent Days (Optional)
      description: >-
        Number of recent days of history to KEEP for the targeted entities. 
        Set to 0 to purge ALL history for these entities.
      selector:
        number:
          min: 0
          max: 30 # Sensible maximum
          unit_of_measurement: days
          mode: box
      default: 0 # Default to purging all history

trigger:
  - platform: time
    at: "03:05:00" 

condition: [] # No conditions needed by default

action:
  - service: recorder.purge_entities
    # Schritt 1: Variablen definieren, die an das 'data'-Template 端bergeben werden
    variables:
      # Hole den Wert aus dem Blueprint Input 'target_label'
      label_to_purge: !input target_label 
      # Hole den Wert aus dem Blueprint Input 'keep_days'
      days_to_keep_config: !input keep_days 
    # Schritt 2: Das 'data'-Template verwendet die oben definierten Variablen
    data: >
      {# Nutze die Variable 'label_to_purge' #}
      {% set entities_to_purge = label_entities(label_to_purge) %}
      
      {# Basis-Datenstruktur f端r den Service Call #}
      {% set service_data = {'entity_id': entities_to_purge} %}
      
      {# F端ge 'keep_days' hinzu, wenn der Wert aus der Variable > 0 ist #}
      {# Nutze die Variable 'days_to_keep_config' #}
      {% if days_to_keep_config > 0 %}
        {% set _ = service_data.update({'keep_days': days_to_keep_config}) %}
      {% endif %}
      
      {# Gib das finale Daten-Dictionary zur端ck #}
      {{ service_data }}
  - delay: 
      seconds: 5 
